services:
  - type: web
    name: bughive
    runtime: static
    buildCommand: npm install && npx vite build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
